// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodoList: typeof import('./components/AddTodoList.vue')['default']
    'CarbonAdd:filled': typeof import('~icons/carbon/add-filled')['default']
    CarbonAddAlt: typeof import('~icons/carbon/add-alt')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    NewTaskItem: typeof import('./components/NewTaskItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
    TodoListDetail: typeof import('./components/TodoListDetail.vue')['default']
    TodoListDetails: typeof import('./components/TodoListDetails.vue')['default']
    Web3: typeof import('./components/Web3.vue')['default']
  }
}

export { }
